// VietQR supported banks list - https://www.vietqr.io/danh-sach-ngan-hang
export const VIETQR_BANKS = [
  { code: '970422', bin: '970422', name: 'MB Bank', shortName: 'MB', logo: 'https://api.vietqr.io/img/MB.png' },
  { code: '970436', bin: '970436', name: 'Vietcombank', shortName: 'VCB', logo: 'https://api.vietqr.io/img/VCB.png' },
  { code: '970418', bin: '970418', name: 'BIDV', shortName: 'BIDV', logo: 'https://api.vietqr.io/img/BIDV.png' },
  { code: '970407', bin: '970407', name: 'Techcombank', shortName: 'TCB', logo: 'https://api.vietqr.io/img/TCB.png' },
  { code: '970415', bin: '970415', name: 'Vietinbank', shortName: 'ICB', logo: 'https://api.vietqr.io/img/ICB.png' },
  { code: '970405', bin: '970405', name: 'Agribank', shortName: 'VBA', logo: 'https://api.vietqr.io/img/VBA.png' },
  { code: '970416', bin: '970416', name: 'ACB', shortName: 'ACB', logo: 'https://api.vietqr.io/img/ACB.png' },
  { code: '970432', bin: '970432', name: 'VPBank', shortName: 'VPB', logo: 'https://api.vietqr.io/img/VPB.png' },
  { code: '970423', bin: '970423', name: 'TPBank', shortName: 'TPB', logo: 'https://api.vietqr.io/img/TPB.png' },
  { code: '970448', bin: '970448', name: 'OCB', shortName: 'OCB', logo: 'https://api.vietqr.io/img/OCB.png' },
  { code: '970403', bin: '970403', name: 'Sacombank', shortName: 'STB', logo: 'https://api.vietqr.io/img/STB.png' },
  { code: '970441', bin: '970441', name: 'VIB', shortName: 'VIB', logo: 'https://api.vietqr.io/img/VIB.png' },
  { code: '970443', bin: '970443', name: 'SHB', shortName: 'SHB', logo: 'https://api.vietqr.io/img/SHB.png' },
  { code: '970437', bin: '970437', name: 'HDBank', shortName: 'HDB', logo: 'https://api.vietqr.io/img/HDB.png' },
  { code: '970454', bin: '970454', name: 'VietCapital Bank', shortName: 'VCCB', logo: 'https://api.vietqr.io/img/VCCB.png' },
  { code: '970449', bin: '970449', name: 'LienVietPostBank', shortName: 'LPB', logo: 'https://api.vietqr.io/img/LPB.png' },
  { code: '970431', bin: '970431', name: 'Eximbank', shortName: 'EIB', logo: 'https://api.vietqr.io/img/EIB.png' },
  { code: '970426', bin: '970426', name: 'MSB', shortName: 'MSB', logo: 'https://api.vietqr.io/img/MSB.png' },
  { code: '970414', bin: '970414', name: 'OceanBank', shortName: 'OCEANBANK', logo: 'https://api.vietqr.io/img/OCEANBANK.png' },
  { code: '970427', bin: '970427', name: 'VietABank', shortName: 'VAB', logo: 'https://api.vietqr.io/img/VAB.png' },
  { code: '970419', bin: '970419', name: 'NCB', shortName: 'NCB', logo: 'https://api.vietqr.io/img/NCB.png' },
  { code: '970428', bin: '970428', name: 'NamABank', shortName: 'NAB', logo: 'https://api.vietqr.io/img/NAB.png' },
  { code: '970406', bin: '970406', name: 'DongABank', shortName: 'DOB', logo: 'https://api.vietqr.io/img/DOB.png' },
  { code: '970429', bin: '970429', name: 'SeABank', shortName: 'SEAB', logo: 'https://api.vietqr.io/img/SEAB.png' },
  { code: '970424', bin: '970424', name: 'ShinhanBank', shortName: 'SHBVN', logo: 'https://api.vietqr.io/img/SHBVN.png' },
  { code: '970433', bin: '970433', name: 'VietBank', shortName: 'VIETBANK', logo: 'https://api.vietqr.io/img/VIETBANK.png' },
  { code: '970452', bin: '970452', name: 'KienlongBank', shortName: 'KLB', logo: 'https://api.vietqr.io/img/KLB.png' },
  { code: '970430', bin: '970430', name: 'PGBank', shortName: 'PGB', logo: 'https://api.vietqr.io/img/PGB.png' },
  { code: '970400', bin: '970400', name: 'Saigonbank', shortName: 'SGB', logo: 'https://api.vietqr.io/img/SGB.png' },
  { code: '970425', bin: '970425', name: 'BacABank', shortName: 'BAB', logo: 'https://api.vietqr.io/img/BAB.png' },
  { code: '970434', bin: '970434', name: 'IndovinaBank', shortName: 'IVB', logo: 'https://api.vietqr.io/img/IVB.png' },
  { code: '970439', bin: '970439', name: 'PublicBank', shortName: 'PBVN', logo: 'https://api.vietqr.io/img/PBVN.png' },
  { code: '970440', bin: '970440', name: 'Co-opBank', shortName: 'COOPBANK', logo: 'https://api.vietqr.io/img/COOPBANK.png' },
  { code: '970446', bin: '970446', name: 'CIMB Vietnam', shortName: 'CIMB', logo: 'https://api.vietqr.io/img/CIMB.png' },
  { code: '970409', bin: '970409', name: 'BaoVietBank', shortName: 'BVB', logo: 'https://api.vietqr.io/img/BVB.png' },
  { code: '970412', bin: '970412', name: 'PVcomBank', shortName: 'PVCB', logo: 'https://api.vietqr.io/img/PVCB.png' },
  { code: '970438', bin: '970438', name: 'BaoViet Securities', shortName: 'BVSC', logo: 'https://api.vietqr.io/img/BVSC.png' },
  { code: '970462', bin: '970462', name: 'KBank', shortName: 'KBANK', logo: 'https://api.vietqr.io/img/KBANK.png' },
  { code: '970463', bin: '970463', name: 'UBank', shortName: 'UBANK', logo: 'https://api.vietqr.io/img/UBANK.png' },
  { code: '970457', bin: '970457', name: 'Woori Bank', shortName: 'WVN', logo: 'https://api.vietqr.io/img/WVN.png' },
];

export const getBankByCode = (code: string) => VIETQR_BANKS.find(b => b.code === code || b.bin === code);
